#Used to specify a motor schema to enable/disable.
string schema	#name of the schema to toggle
bool state #true for enabled, false for disabled
---
bool result	#true if the request was accepted. False if rejected.
