define sofa1 position
(
  size [1 1 1]	
   block #BASE
   (
      points 8
      point[0]  [ 0.5 0]
      point[1]  [ 4.5 0]
      point[2]  [ 5   0.5]
      point[3]  [ 5   3.5]
      point[4]  [ 4.5 4]
      point[5]  [ 0.5 4]
      point[6]  [ 0   3.5]
      point[7]  [ 0   0.5] 
      z [0 0.5]
   )
   block #HAND1
   (
      points 7
      point[0]  [ 0.5 0]
      point[1]  [ 1 0]
      point[2]  [ 1.5   0.5]
      point[3]  [ 1.5   2.5]
      point[4]  [ 0.5   2.5]
      point[5]  [ 0 3]
      point[6]  [ 0   0.5] 
      z [0.5 0.7]
   )
   block #HAND2
   (
      points 7
      point[0]  [ 4 0]
      point[1]  [ 4.5 0]
      point[2]  [ 5   0.5]
      point[3]  [ 5   3]
      point[4]  [ 4.5 2.5]
      point[5]  [ 3.5 2.5]
      point[6]  [ 3.5   0.5] 
      z [0.5 0.7]
   )
   block #BACK
   (
      points 8
      point[0]  [ 0.5 2.5]
      point[1]  [ 4.5 2.5]
      point[2]  [ 5   3]
      point[3]  [ 5   3.5]
      point[4]  [ 4.5 4]
      point[5]  [ 0.5 4]
      point[6]  [ 0   3.5]
      point[7]  [ 0   3] 
      z [0.5 1]
   )
   color "yellow"	
)
