define trash_bin position
(
  size [0.4 0.4 0.4]	
   block #trash bin
   (
      points 12
      point[0]  [ 1 -15.5]
      point[1]  [ 3 -14.5]
      point[2]  [ 4 -12.5]
      point[3]  [ 4 -10.5]
      point[4]  [ 3 -8.5]
      point[5]  [ 1 -7.5]
      point[6]  [-1 -7.5]
      point[7]  [-3 -8.5]
      point[8]  [-4 -10.5]
      point[9]  [-4 -12.5]
      point[10] [-3 -14.5]
      point[11] [-1 -15.5]
      z [0 0.4]
   )
   color "red"	
)
