#This is how a collection of tasks are requested to the TaskHandler.

#Goal parameters: List of the task requests. Each item in tasks corresponds with the same index element in parameters
arc_msgs/TaskRequest tasks
---
#Eventually a summary of all the tasks for this request will go here.
---
#this will contain an individual task response


